# Generated by Django 4.2.5 on 2023-09-13 23:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicines', '0004_alter_medication_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=True, verbose_name='Архив')),
                ('title', models.CharField(max_length=100, verbose_name='Название купона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления на сайт')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание вакансии')),
                ('salary', models.PositiveIntegerField(verbose_name='Предлагаемая зарплата')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.RemoveField(
            model_name='medication',
            name='photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание выполняемых работ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=20, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%n/%d/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medication', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название филлиала аптеки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.department', verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicationcategory', verbose_name='Категория препарата'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание лекарства'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Есть ли в продаже'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество доступных'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название лекарства'),
        ),
        migrations.AlterField(
            model_name='medicationcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.employee', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medication', verbose_name='Продаваемое лекарство'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество проданных'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефонный номер'),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Рейтинг должен быть не меньше 0.'), django.core.validators.MaxValueValidator(5, message='Рейтинг должен быть не больше 5.')], verbose_name='Рейтинг')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
