# Generated by Django 4.2.5 on 2023-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_coupon_faq_vacancy_remove_medication_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('article', models.TextField(blank=True, verbose_name='Вся статья')),
                ('image', models.ImageField(blank=True, upload_to='static/medicines/images/news')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/medicines/photos'),
        ),
    ]
