# Generated by Django 4.2.5 on 2023-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(null=True, verbose_name='Ссылка на статью'),
        ),
    ]
