# Generated by Django 4.2.5 on 2023-12-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название купона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discount', models.PositiveIntegerField(verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Promocode',
                'verbose_name_plural': 'Promocodes',
            },
        ),
    ]
