# Generated by Django 4.2.5 on 2023-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(verbose_name='Процент скидки'),
        ),
    ]
